# Section3 | 파이썬 기초

## 파이썬 자료형

In [1]:
# 1. 정수형, 실수형
a = 123
b = -123.4
a+b

-0.4000000000000057

In [2]:
# 2. 8진수
c = 0o34
d = 0o24
c+d

48

In [3]:
# 3. 16진수
e = 0x2A
f = 0xFF
e+f

297

## 문자형(String)

In [6]:
# 문자열
# 단일 인용 표시('': 작은 따옴표) or 이중 인용 표시("": 큰 따옴표)
s = 'WiseInCompany'
s1 = 'WiseIncompany'
s2 = '''WiseInCompany'''
s3 = "123"
print(s)
print(s1)
print(s2)
print(s3)
print(type(s3))

WiseInCompany
WiseIncompany
WiseInCompany
123
<class 'str'>


In [7]:
# 문자열 연산하기
a = "Wise"
b = "InCompany"
print(a+b)
a = "WiseInCompany"
print(a*2)

WiseInCompany
WiseInCompanyWiseInCompany


In [8]:
# 문자열 인덱싱 및 슬라이싱
a = "Wise In Company"
print(a[3]) 
print(a[-3]) 
print(a[0:15])
print(a[4:])
print(a[0:4])

e
a
Wise In Company
 In Company
Wise


## 리스트(List)

In [10]:
# 리스트
a = [1,2,3,4,5]
print(f'a : {a}')
# 리스트 인덱싱
a = [1,2,3,4,5]
print(f'a[0] : {a[0]}')
print(f'a[-1] : {a[-1]}')
# 리스트 슬라이싱
a = [1,2,3,4,5]
print(f'a[0:5] : {a[0:5]}')
print(f'a[:5] : {a[:5]}')
print(f'a[2:] : {a[2:]}')

a : [1, 2, 3, 4, 5]
a[0] : 1
a[-1] : 5
a[0:5] : [1, 2, 3, 4, 5]
a[:5] : [1, 2, 3, 4, 5]
a[2:] : [3, 4, 5]


In [15]:
# 리스트 요소 추가/수정/삭제

a = [1,2,3,4,5]
a.append(6) # 추가
print(f'a.append(6) {a}')
a[0] = 0 # 1 -> 0
print(f'a[0] = 0 : {a}')
del a[1] # 1번째 자리 삭제
print(f'del a[1] : {a}')

a.append(6) [1, 2, 3, 4, 5, 6]
a[0] = 0 : [0, 2, 3, 4, 5, 6]
del a[1] : [0, 3, 4, 5, 6]


In [16]:
# 리스트 병합 및 반복
a = [1, 2]
b = [3, 4, 5]
c = a + b
print(c)
d = a*3
print(d)

[1, 2, 3, 4, 5]
[1, 2, 1, 2, 1, 2]


## 튜플(Tuple)
-> 소괄호( )

In [17]:
# 튜플
t = (1, 2, 3, 4, 5)
# 튜플 인덱싱 및 슬라이싱
t1 = (1, 2, 3)
print(t[1]) # 인덱싱
print(t[0:3]) # 슬라이싱

2
(1, 2, 3)


In [18]:
# 튜플 병합 및 반복
a = (1, 2)
b = (3, 4, 5)
c = a + b
print(c)
d = a * 3
print(d)

(1, 2, 3, 4, 5)
(1, 2, 1, 2, 1, 2)


In [21]:
# 튜플 변수 할당
name = ("David", "Kim")
print(name)
firstname, lastname = ("David", "Kim")
print(f'listname : {lastname} , firstname : {firstname}')

('David', 'Kim')
listname : Kim , firstname : David


## 집합(Set)
-> 중복된 값이 들어가지 않는 자료형  
-> 중괄호({ })로 표현  
-> 차집합, 합집합, 교집합( -, +, & )등으로 집합 목록으로 변경가능  

In [22]:
# 집합
set = {1, 1, 2, 3}
print(set)

{1, 2, 3}


In [23]:
# 집합 추가 및 삭제1
set = {1, 1, 2, 3}
set.add(4) # 요소 추가
set

{1, 2, 3, 4}

In [24]:
# 집합 추가 및 삭제2
set = {1, 1, 2, 3}
set.update({4, 5, 6}) # 요소 여러 개 추가
set

{1, 2, 3, 4, 5, 6}

In [25]:
# 요소 하나 삭제
set.remove(1)
set

{2, 3, 4, 5, 6}

In [26]:
set.clear()
set

set()

In [27]:
# 집합 연산
a = {1, 2, 3}
b = {1, 3, 4}

# 교집합
c = a & b
print(c)

# 합집합
d = a|b
print(d)

# 차집합
e = a-b
print(e)

{1, 3}
{1, 2, 3, 4}
{2}


## 사전(Dictionary)
-> 키(Key)와 값(Value)으로 이루어진 자료형  
-> 집합처럼 중괄호로({ })로 표현

In [28]:
# 사전
test = {"Kim" : 90, "Jeong" : 80, "Park" : 75}
test["Kim"] # 키 이용

90

In [32]:
# 사전 추가/수정/삭제
test = {"Kim" : 90, "Jeong" : 80, "Park" : 75}
test["Jeong"] = 85
test["Cho"] = 95
print(test)
del test["Park"]
print(test)

{'Kim': 90, 'Jeong': 85, 'Park': 75, 'Cho': 95}
{'Kim': 90, 'Jeong': 85, 'Cho': 95}


In [33]:
# 키 또는 값 가져오기
test = {"Kim" : 90, "Jeong" : 80, "Park" : 75}
print(test.keys()) # 키 가져오기
print(test.values()) # 값 가져오기

dict_keys(['Kim', 'Jeong', 'Park'])
dict_values([90, 80, 75])


## if문

In [35]:
# if (조건문):  
#     명령어 1  
# elif (조건문):  
#     명령어 2  
# else:  
#     명령어 3  
###################################  
# x < y : x가 y보다 작다
# x > y : x가 y보다 크다
# x == y : x와 y가 같다
# x != y : x와 y가 같지 않다
# x >= y : x가 y보다 크거나 같다
# x <= y : x가 y보다 작너나 같다.

In [36]:
# if문 예시
money = 4000
if money == 3000:
    print("KTX")
elif money >= 5000:
    print('Bus')
else:
    print('Walk')

Walk


## 반복문

In [1]:
# for문 기본
sum = 0
for i in range(11):
    sum = sum+i
print(sum)

55


In [2]:
# for문 리스트 출력
list = ["Wise", "In", "Company"]
for s in list:
    print(s)

Wise
In
Company


In [3]:
# while문 기본
i = 0
while i < 10:
    print(i)
    i = i+1

0
1
2
3
4
5
6
7
8
9


In [5]:
# while문 리스트 출력
food = ['apple','banana','bread']
i = 0
while i < len(food):
    print(food[i])
    i = i+1

apple
banana
bread


# Section4 | Numpy 함수
-> 과학 계산을 위한 파이썬 데이터 분석 패키지   
-> 다차원 배열을 처리하는데 필요한 여러 유용한 기능을 제공  

| 함 수 | 설 명 | 사용법 |  
|:---:|:---:|:---:|  
| abs, fabs | 절대값을 리턴, 복소수가 아닌 경우에는 빠른 연산을 위해 fabs이용 | numpy.sb(arr)|
| sqrt | 제곱근 ( 루트 )을 계산 | numpy.sqrt(arr)|
| square | 제곱 계산 | numpy.square(arr) |
| exp | 지수 계산 | numpy.exp(arr) |
| Log | 로그 계산 | numpy.Log(arr) |
| add | 두 배열을 더한다 | numpy.add(arr1, arr2)
| subtract | 첫 번째 배열에서 두 번째 배열을 뺀다. | numpy.subtract(arr1, arr2) |
| multiply | 두 배열을 곱한다. | numpy.multiply(arr1, arr2) |

## numpy 배열 생성

In [3]:
# numpy 배열 기본
import numpy as np
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [4]:
# np.arange(시작 값, 끝 깞, 간격) or np.arange(끝값)
# 연속되거나 일정한 규칙을 가진 숫자
v1 = np.arange(5)
print(v1)
# 연속되거나 일정한 규칙을 가진 숫자, 데이터 형태 지정
v2 = np.arange(1, 10, 2, dtype = int)
v3 = np.arange(3.5, 10.5, 2, dtype = float)
print(v2)
print(v3)
# 제곱값 생성
v4 = np.arange(1, 10, 2) **2
print(v4)
# 세제곱값 생성
v5 = np.arange(1, 10, 2) **3
print(v5)

[0 1 2 3 4]
[1 3 5 7 9]
[3.5 5.5 7.5 9.5]
[ 1  9 25 49 81]
[  1  27 125 343 729]


## 행렬 만들기
명령어 : np.reshape(차원, 행, 렬, order = 'C' or 'F')  
order = 'C' : 값을 행부터 채워 넣음(기본값, 생략 가능)  
order = 'F': 값을 열부터 채워 넣음

In [7]:
# 행렬만들기
v1 = np.arange(12)
print(v1)
# order = 'C' (default) 행부터 집어 넣음
v2 = v1.reshape(2, 6)
print(v2)
# order = 'F' 열부터 집어 넣음
v3 = v1.reshape(2, 6, order = 'F')
print(v3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


np.add(변수명, 변수명) # 덧셈  
np.subtract(변수명, 변수명) # 뺄셈  
np.multiply(변수명, 변수명) # 곱셈  
np.dot(변수명, 변수명) # 행렬 연산  

In [13]:
# 행렬계산
v1 = np.arange(1,5).reshape(2,2)
print(f'덧셈 \n {np.add(v1,v1)}')
print(f'뺄셈 \n {np.subtract(v1,v1)}')
print(f'곱셈 \n {np.multiply(v1,v1)}')
print(f'행렬연산 \n {np.dot(v1,v1)}')

덧셈 
 [[2 4]
 [6 8]]
뺄셈 
 [[0 0]
 [0 0]]
곱셈 
 [[ 1  4]
 [ 9 16]]
행렬연산 
 [[ 7 10]
 [15 22]]


## 다차원 배열 만들기

In [16]:
# 다차원 행렬 만들기
v1 = np.arange(12)
print(v1)
v2 = v1.reshape(2, 3, 2, order = 'F')
print(v2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


In [20]:
# 명령어 : np.amax(변수명) (최대값); np.amin(변수명) 최소값
# 명령어 : 변수명.dtype
# 명령어 : 변수명.shape
# 다차원 배열에서 요소의 최대값 및 최소값 반환
v3 = np.arange(3.5, 10.5, 2, dtype = float)
print(v3)
v4 = np.arange(1,5).reshape(2,2)
print(v4)
print(np.amax(v3))
print(np.amin(v4))
print(v3.dtype)
print(v4.shape)

[3.5 5.5 7.5 9.5]
[[1 2]
 [3 4]]
9.5
1
float64
(2, 2)


# Section 05 | pandas와 기본 데이터 처리
Pandas  
I. Series  
-> index와 value의 형태를 갖고 있는 pandas의 자료구조  
II. DataFrmae  

In [120]:
continent = np.random.randint(2,size=(63))
brand = np.random.randint(3, size = (63))
size = np.random.uniform(0.0,35.0, size = 63)
period = np.random.uniform(0.0,65.0, size = 63)
price = np.random.randint(200, size = (63))

In [121]:
#[ x for x in (continent,brand,size,period,price)]
df = pd.DataFrame((zip(continent,brand,size,period,price)), columns = ['continent','brand','size','period','price'])

In [122]:
df.to_csv('./EX_GrapeData.csv', index = False)

In [123]:
df

continent  brand       size     period  price
0           0      1  10.743977  27.078756     90
1           1      0  23.730386  46.649410     92
2           1      1  23.396368   5.288003    103
3           1      2  20.968568   4.939850     90
4           0      1   1.256931  24.809650    193
..        ...    ...        ...        ...    ...
58          1      1  24.791871  51.281930    126
59          0      1  25.445968  10.142605    133
60          1      0   5.172596  18.332103    193
61          0      2  33.988714  54.186807    123
62          0      2  21.737415  28.479418     47

[63 rows x 5 columns]

In [124]:
#pandas 함수 불러오기
import pandas as pd
from pandas import Series, DataFrame
# series 설정
a = Series([1, 3, 5, 7])
print(a)
print(a.values)
print(a.index)
# index 변경
a2 = pd.Series([1, 3, 5, 7], index = ['a', 'b', 'c', 'd'])
print(a2)

0    1
1    3
2    5
3    7
dtype: int64
[1 3 5 7]
RangeIndex(start=0, stop=4, step=1)
a    1
b    3
c    5
d    7
dtype: int64


### 5.2 데이터 불러오기
CSV파일 불러오기 : pd.read_csv('파일명.csv')

In [125]:
# csv파일을 pandas DataFrame 형태로 불러오기
df = pd.read_csv('EX_GrapeData.csv')
df

continent  brand       size     period  price
0           0      1  10.743977  27.078756     90
1           1      0  23.730386  46.649410     92
2           1      1  23.396368   5.288003    103
3           1      2  20.968568   4.939850     90
4           0      1   1.256931  24.809650    193
..        ...    ...        ...        ...    ...
58          1      1  24.791871  51.281930    126
59          0      1  25.445968  10.142605    133
60          1      0   5.172596  18.332103    193
61          0      2  33.988714  54.186807    123
62          0      2  21.737415  28.479418     47

[63 rows x 5 columns]

In [126]:
# 엑셀파일을 pandas DataFrame 형태로 불러오기
# df = pd.read_excel('EX_GrapeData.xlsx')
# df

In [127]:
# 한글이 깨지는 경우
# df = pd.read_csv('cosmetics_.csv', encoding = 'euc-kr')
# df = pd.read_excel('cosmetics_.xlsx', encoding = 'euc-kr')

### DataFrame 확인하기

In [128]:
# 데이터 프레임 처음부터 ~개의 행만 불러오기
# 명령어 : 변수명.head(불러올 행 개수, 공백시 5개)
df.head()

continent  brand       size     period  price
0          0      1  10.743977  27.078756     90
1          1      0  23.730386  46.649410     92
2          1      1  23.396368   5.288003    103
3          1      2  20.968568   4.939850     90
4          0      1   1.256931  24.809650    193

In [129]:
# 데이터 프레임 뒤에서부터 ~개의 행만 불러오기
# 명령어 : 변수명.tail(불러올 행 개수, 공백시 5개)
df.tail()

continent  brand       size     period  price
58          1      1  24.791871  51.281930    126
59          0      1  25.445968  10.142605    133
60          1      0   5.172596  18.332103    193
61          0      2  33.988714  54.186807    123
62          0      2  21.737415  28.479418     47

In [130]:
# 데이터 프레임에서 특정한 연속적 행을 확인
# 명렁어 : 변수명[처음 출력할 행 : 마지막으로 출력할 행 + 1]
# 1에서 4까지 출력
df[1:5]

continent  brand       size     period  price
1          1      0  23.730386  46.649410     92
2          1      1  23.396368   5.288003    103
3          1      2  20.968568   4.939850     90
4          0      1   1.256931  24.809650    193

In [131]:
# 처음부터 2까지 출력하기
df[:3]

continent  brand       size     period  price
0          0      1  10.743977  27.078756     90
1          1      0  23.730386  46.649410     92
2          1      1  23.396368   5.288003    103

In [132]:
# 60에서 끝까지 출력
df[60:]

continent  brand       size     period  price
60          1      0   5.172596  18.332103    193
61          0      2  33.988714  54.186807    123
62          0      2  21.737415  28.479418     47

In [133]:
# 열 불러오기
# I. 데이터셋명[['열 이름']
# II. 데이터셋명[데이터셋명.columns[[열 번호]]
# III. 데이터셋명.loc[:, 첫 행 이름; 끝 열 이름]

# price 변수(열) 불러오기 : series 형태
df['price'] # df.price으로 대체 가능

0      90
1      92
2     103
3      90
4     193
     ... 
58    126
59    133
60    193
61    123
62     47
Name: price, Length: 63, dtype: int64

In [134]:
# price 변수(열) 불러오기 : DataFrame 형태
df[['price']]

price
0      90
1      92
2     103
3      90
4     193
..    ...
58    126
59    133
60    193
61    123
62     47

[63 rows x 1 columns]

In [135]:
# 0번, 2번, 4번째 열(컬럼)만 출력
df[df.columns[[0,2,4]]]

continent       size  price
0           0  10.743977     90
1           1  23.730386     92
2           1  23.396368    103
3           1  20.968568     90
4           0   1.256931    193
..        ...        ...    ...
58          1  24.791871    126
59          0  25.445968    133
60          1   5.172596    193
61          0  33.988714    123
62          0  21.737415     47

[63 rows x 3 columns]

In [136]:
# loc명령어를 사용해서 원하는 열 (변수) 불러오기 
# [:, '변수명' : '변수명']
# size부터 price까지 출력
df.loc[:, 'size':'price']

size     period  price
0   10.743977  27.078756     90
1   23.730386  46.649410     92
2   23.396368   5.288003    103
3   20.968568   4.939850     90
4    1.256931  24.809650    193
..        ...        ...    ...
58  24.791871  51.281930    126
59  25.445968  10.142605    133
60   5.172596  18.332103    193
61  33.988714  54.186807    123
62  21.737415  28.479418     47

[63 rows x 3 columns]

In [137]:
# 데이터 프레임의 특정 행과 열을 지정 iloc
# 명령어 : 변수명.iloc[첫 행: 끝 행, 첫 열 : 끝 열]
# 1~7행(케이스), 0~2열(변수)만 불러오기
df.iloc[1:7, 0:2]

continent  brand
1          1      0
2          1      1
3          1      2
4          0      1
5          1      2
6          1      0

In [138]:
# 특정한 하나의 값을 지정해서 불러오려면 at
# 명령어 : 변수명.at [행 번호, '열 이름']
# 4행(케이스)의 price 변수 해당 값 불러오기
df.at[4, 'price']

193

### 5.3 데이터 변환하기

In [155]:
# 데이터 프레임 행 복사(백업)
df_columns = df.copy()

In [156]:
# 데이터 프레임의 열(변수) 이름 확인
df_columns.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [157]:
df_columns

continent  brand       size     period  price
0           0      1  10.743977  27.078756     90
1           1      0  23.730386  46.649410     92
2           1      1  23.396368   5.288003    103
3           1      2  20.968568   4.939850     90
4           0      1   1.256931  24.809650    193
..        ...    ...        ...        ...    ...
58          1      1  24.791871  51.281930    126
59          0      1  25.445968  10.142605    133
60          1      0   5.172596  18.332103    193
61          0      2  33.988714  54.186807    123
62          0      2  21.737415  28.479418     47

[63 rows x 5 columns]

In [158]:
df_columns

continent  brand       size     period  price
0           0      1  10.743977  27.078756     90
1           1      0  23.730386  46.649410     92
2           1      1  23.396368   5.288003    103
3           1      2  20.968568   4.939850     90
4           0      1   1.256931  24.809650    193
..        ...    ...        ...        ...    ...
58          1      1  24.791871  51.281930    126
59          0      1  25.445968  10.142605    133
60          1      0   5.172596  18.332103    193
61          0      2  33.988714  54.186807    123
62          0      2  21.737415  28.479418     47

[63 rows x 5 columns]

In [159]:
# 데이터 프레임 열들 중에서 일부 열(변수)만 필터링하여 기존 혹은 새로운 데이터 셋을 구성
# 데이터 프레임 열 필터링
# df_columns2 = df_columns[['gender','marriage','edu','job','mincome']]
# df_columns2.head()

In [160]:
# 데이터 열(변수) 이름 수정 : period -> time
df_columns.rename(columns = {'period':'time'},inplace = True)
df_columns.columns

Index(['continent', 'brand', 'size', 'time', 'price'], dtype='object')

In [161]:
# size를 time으로 나누어 월별 포도크기로 계산하여 growth 변수 생성
df_columns['growth'] = df_columns['size']/df_columns['time']
df_columns.head()

continent  brand       size       time  price    growth
0          0      1  10.743977  27.078756     90  0.396768
1          1      0  23.730386  46.649410     92  0.508696
2          1      1  23.396368   5.288003    103  4.424424
3          1      2  20.968568   4.939850     90  4.244778
4          0      1   1.256931  24.809650    193  0.050663

In [162]:
# 특정 변수 삭제: growth 삭제
del df_columns['growth']

In [163]:
# 특정 케이스 선택1 : 집단선택
df_continent_brand = df[(df['continent']==1) & (df['brand']==1)]
df_continent_brand.head()

continent  brand       size     period  price
2           1      1  23.396368   5.288003    103
9           1      1   1.150915  32.004155     94
18          1      1  19.573135  46.414933    135
26          1      1   6.950187  26.253114     41
32          1      1  17.992321  45.114512     14

### 코딩변경
I. replace 기능  
II. 함수로 정의  

In [164]:
# brand 범주 카운트
df['brand'].value_counts()

2    25
1    20
0    18
Name: brand, dtype: int64

In [165]:
recode_brand = {'brand':{1: 1, 2: 1, 3: 2}}
df_recode1 = df.replace(recode_brand)
df_recode1.head()

continent  brand       size     period  price
0          0      1  10.743977  27.078756     90
1          1      0  23.730386  46.649410     92
2          1      1  23.396368   5.288003    103
3          1      1  20.968568   4.939850     90
4          0      1   1.256931  24.809650    193

In [166]:
df_recode1['brand'].value_counts()

1    45
0    18
Name: brand, dtype: int64

In [168]:
# brand 1, 2, 3 집단을 1, 2로 묶기 (1/2 -> 1, 3 -> 2)
def brand_groups(series):
    if series == 1:
        return 1
    elif series == 2:
        return 1
    elif series == 3:
        return 2
    
df['re_brand'] = df['brand'].apply(brand_groups)
df.head()

continent  brand       size     period  price  re_brand
0          0      1  10.743977  27.078756     90       1.0
1          1      0  23.730386  46.649410     92       NaN
2          1      1  23.396368   5.288003    103       1.0
3          1      2  20.968568   4.939850     90       1.0
4          0      1   1.256931  24.809650    193       1.0

### pandas와 numpy 전환

In [169]:
import pandas as pd
df = pd.read_csv('EX_GrapeData.csv')
df.head()

continent  brand       size     period  price
0          0      1  10.743977  27.078756     90
1          1      0  23.730386  46.649410     92
2          1      1  23.396368   5.288003    103
3          1      2  20.968568   4.939850     90
4          0      1   1.256931  24.809650    193

In [170]:
# 판다스를 넘파이로 변환 .to_numpy()라고 선언
df_num = df.to_numpy()
df_num

array([[0.00000000e+00, 1.00000000e+00, 1.07439770e+01, 2.70787562e+01,
        9.00000000e+01],
       [1.00000000e+00, 0.00000000e+00, 2.37303857e+01, 4.66494096e+01,
        9.20000000e+01],
       [1.00000000e+00, 1.00000000e+00, 2.33963679e+01, 5.28800341e+00,
        1.03000000e+02],
       [1.00000000e+00, 2.00000000e+00, 2.09685676e+01, 4.93985029e+00,
        9.00000000e+01],
       [0.00000000e+00, 1.00000000e+00, 1.25693146e+00, 2.48096505e+01,
        1.93000000e+02],
       [1.00000000e+00, 2.00000000e+00, 3.07400362e+01, 4.74164018e+01,
        4.40000000e+01],
       [1.00000000e+00, 0.00000000e+00, 2.01332515e+01, 6.12596452e+01,
        1.67000000e+02],
       [0.00000000e+00, 1.00000000e+00, 1.46339687e+01, 5.81838098e+01,
        1.75000000e+02],
       [0.00000000e+00, 0.00000000e+00, 5.40268319e+00, 4.32974069e+01,
        1.90000000e+01],
       [1.00000000e+00, 1.00000000e+00, 1.15091468e+00, 3.20041546e+01,
        9.40000000e+01],
       [0.00000000e+00, 0.0000

In [171]:
df_pd = pd.DataFrame(df_num)
df_pd.head()

0    1          2          3      4
0  0.0  1.0  10.743977  27.078756   90.0
1  1.0  0.0  23.730386  46.649410   92.0
2  1.0  1.0  23.396368   5.288003  103.0
3  1.0  2.0  20.968568   4.939850   90.0
4  0.0  1.0   1.256931  24.809650  193.0

In [172]:
df_pd2 = pd.DataFrame(data = df_num, columns = ['continent', 'brand','size','period','price'])
df_pd2.head()

continent  brand       size     period  price
0        0.0    1.0  10.743977  27.078756   90.0
1        1.0    0.0  23.730386  46.649410   92.0
2        1.0    1.0  23.396368   5.288003  103.0
3        1.0    2.0  20.968568   4.939850   90.0
4        0.0    1.0   1.256931  24.809650  193.0